[Appearance]
color_scheme_path=/home/celal/.config/qt5ct/colors/matugen.conf
custom_palette=true
icon_theme=Tela-dracula
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Cantarell,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
general="Cantarell,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
