foreground         #c2c0c2
background         #0e060b
background_opacity 1.0
cursor             #c2c0c2

active_tab_foreground     #0e060b
active_tab_background     #c2c0c2
inactive_tab_foreground   #c2c0c2
inactive_tab_background   #0e060b

active_border_color   #c2c0c2
inactive_border_color #0e060b
bell_border_color     #2a364c

color0       #0e060b
color8       #695561
color1       #2a364c
color9       #384966
color2       #394153
color10      #4D576F
color3       #7d341b
color11      #A74625
color4       #b47d3f
color12      #F0A755
color5       #42536b
color13      #586F8F
color6       #765a67
color14      #9E798A
color7       #958a92
color15      #c2c0c2
