#!/bin/bash
set -eu 
pkill -x mako || true
pkill -x swayosd-server || true
pkill -x waybar || true
sleep 0.5
start_services() {
    systemctl --user start mako.service
    systemctl --user start waybar.service    
    setsid uwsm-app -- swayosd-server >/dev/null 2>&1 &
}
start_services
