# --- BAŞLANGIÇTA ÇALIŞTIRILACAK UYGULAMALAR ---
exec-once = hypridle
exec-once = waybar
exec-once = swww-daemon
exec-once = swaync
exec-once = swayosd-server
exec-once = hyprsunset
exec-once = swaync-client -df
exec-once = pactl set-sink-mute @DEFAULT_SINK@ 0
exec-once = hyprctl setcursor Qogir 12
exec-once = gsettings set org.gnome.desktop.interface cursor-theme "Qogir-Manjaro"
exec-once = gsettings set org.gnome.desktop.interface cursor-size 12
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --watch cliphist store
exec-once = udiskie -s
exec-once = ~/.config/hypr/gtk.sh
