    $wallpaper = /home/cll/wallpapers/walls/grass.jpg
    $foregroundCol = 0xffc2c2c5
    $backgroundCol = 0xff0c0b1a
    $color0 = 0xff0c0b1a
    $color1 = 0xff350855
    $color2 = 0xff352356
    $color3 = 0xff363358
    $color4 = 0xff410a67
    $color5 = 0xff4e1679
    $color6 = 0xff4d3a76
    $color7 = 0xff8e8e99
    $color8 = 0xff5c5a6f
    $color9 = 0xff470B72
    $color10 = 0xff472F73
    $color11 = 0xff484576
    $color12 = 0xff570E8A
    $color13 = 0xff691EA2
    $color14 = 0xff674E9E
    $color15 = 0xffc2c2c5
