general {
    col.active_border = rgba(8c9198AA)
    col.inactive_border = rgba(42474eAA)
}

misc {
    background_color = rgba(101418FF)
}
windowrulev2 = bordercolor rgba(9accfaAA) rgba(9accfa77),pinned:1