# --- HYDRLAND ANA YAPILANDIRMA ---

# Kaynak Dosyaları
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/exec-once.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windowsrule.conf

# Monitor Ayarları
monitor = ,1920x1080@60,auto,1
#monitor=,preferred,auto,1
# XWayland Ayarları
xwayland {
    force_zero_scaling = true
}

# Çeşitli Ayarlar
misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    anr_missed_pings = 5
    allow_session_lock_restore = true
}
