input {
    kb_layout = tr
    follow_mouse = 1
    accel_profile = flat
    numlock_by_default = true
    touchpad {
        natural_scroll = false
        scroll_factor = 1
    }
    repeat_rate = 40
    repeat_delay = 600
}

gesture = 3, horizontal, workspace
gesture = 3, pinchin,float,tile
gesture = 3, pinchout,float, float
gesture = 3, swipe, move,
gesture = 3, down, mod: SUPER, close
gesture = 3, up, mod: SUPER, fullscreen
